In [95]:
import numpy as np

In [96]:
print(len(dir(np)))
dir(np) # to get all the functions in numpy

592


['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [97]:
np.__version__ # to get the version of numpy

'1.26.4'

In [98]:
arr = np.array([1,2,3,4,5]) # to create a numpy array)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [99]:
arr.size

5

In [100]:
arr.shape

(5,)

In [101]:
arr2 = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
arr3 = np.array([[[2],[1]],[[2],[1]]])

In [102]:
np.array([]).shape

(0,)

In [103]:
print(arr2)
print(arr2.shape)
print(arr2.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9


In [104]:
print(arr2[-1][-1])

9


In [105]:
# arr.length
arr2.ndim

2

In [106]:
print(np.array(range(64)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]


In [107]:
arr5 = np.arange(64)

In [108]:
print(arr5.shape)
print(arr5.reshape(4, 16))
print(arr5.reshape(4, 16).ndim)
print(arr5.reshape(4, 16).shape)

(64,)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]]
2
(4, 16)


Brodcasting -> https://numpy.org/doc/stable/user/basics.broadcasting.html

In [109]:
x = [2, ["sf"], {"a": 10}]

In [110]:
np.array(["ad", "afe", "Ad"])

array(['ad', 'afe', 'Ad'], dtype='<U3')

In [111]:
import pandas as pd

In [112]:
print(len(dir(pd)))

141


In [113]:
import pandas as pd

In [114]:
df = pd.read_csv("aadhar.csv")

In [115]:
df

date              state      district  pincode  bio_age_5_17  \
0       01-03-2025            Haryana  Mahendragarh   123029           280   
1       01-03-2025              Bihar     Madhepura   852121           144   
2       01-03-2025  Jammu and Kashmir         Punch   185101           643   
3       01-03-2025              Bihar       Bhojpur   802158           256   
4       01-03-2025         Tamil Nadu       Madurai   625514           271   
...            ...                ...           ...      ...           ...   
499995  19-09-2025              Delhi    West Delhi   110041           102   
499996  19-09-2025              Delhi    West Delhi   110043             8   
499997  19-09-2025              Delhi    West Delhi   110058             7   
499998  19-09-2025                Goa     North Goa   403102             1   
499999  19-09-2025                Goa     North Goa   403106             1   

        bio_age_17_  
0               577  
1               369  
2              1091  
3               980  
4               815  
...             ...  
499995          100  
499996            5  
499997            5  
499998            0  
499999            0  

[500000 rows x 6 columns]

In [117]:
print(df.shape)
print(df.size)
print(df.ndim)

(500000, 6)
3000000
2


In [118]:
df.dtypes

date            object
state           object
district        object
pincode          int64
bio_age_5_17     int64
bio_age_17_      int64
dtype: object

In [119]:
df.describe

<bound method NDFrame.describe of               date              state      district  pincode  bio_age_5_17  \
0       01-03-2025            Haryana  Mahendragarh   123029           280   
1       01-03-2025              Bihar     Madhepura   852121           144   
2       01-03-2025  Jammu and Kashmir         Punch   185101           643   
3       01-03-2025              Bihar       Bhojpur   802158           256   
4       01-03-2025         Tamil Nadu       Madurai   625514           271   
...            ...                ...           ...      ...           ...   
499995  19-09-2025              Delhi    West Delhi   110041           102   
499996  19-09-2025              Delhi    West Delhi   110043             8   
499997  19-09-2025              Delhi    West Delhi   110058             7   
499998  19-09-2025                Goa     North Goa   403102             1   
499999  19-09-2025                Goa     North Goa   403106             1   

        bio_age_17_  
0      

In [130]:
df.bio_age_5_17.quantile(0.7)

17.0

In [129]:
df.bio_age_5_17.max()

8002

In [136]:
df.bio_age_5_17.describe()

count    500000.000000
mean         46.991398
std         156.022633
min           0.000000
25%           1.000000
50%           5.000000
75%          25.000000
max        8002.000000
Name: bio_age_5_17, dtype: float64

In [137]:
df.describe()

pincode   bio_age_5_17    bio_age_17_
count  500000.000000  500000.000000  500000.000000
mean   522548.232572      46.991398      50.462580
std    199084.916346     156.022633     164.379206
min    110001.000000       0.000000       0.000000
25%    390010.000000       1.000000       2.000000
50%    522414.000000       5.000000       6.000000
75%    690527.000000      25.000000      24.000000
max    855456.000000    8002.000000    7625.000000

In [140]:
df[['state']]

state
0                 Haryana
1                   Bihar
2       Jammu and Kashmir
3                   Bihar
4              Tamil Nadu
...                   ...
499995              Delhi
499996              Delhi
499997              Delhi
499998                Goa
499999                Goa

[500000 rows x 1 columns]

In [143]:
print(len(dir(pd)))

141
